-- CRIAÇÃO DO DB
CREATE DATABASE DB_JOINS;
USE DB_JOINS; 

CREATE TABLE cliente (
CODCLI CHAR(3) NOT NULL PRIMARY KEY,
NOME VARCHAR(40) NOT NULL,
ENDERECO VARCHAR(50) NOT NULL,
CIDADE VARCHAR(29) NOT NULL,
ESTADO CHAR(2) NOT NULL,
CEP CHAR(9) NOT NULL 
);

CREATE TABLE venda (
duplic char(6) NOT NULL PRIMARY KEY,
VALOR DECIMAL(10,2) NOT NULL,
VENCTO DATE NOT NULL,
CODCLI CHAR(3) NOT NULL,
FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI)
);


-- INSERÇÃO DE DADOS NA TABELA CLIENTES

INSERT INTO CLIENTE VALUES (
'250',
'BANCO BARCA S/A',
'R. VITO, 34',
'SAO SEBASTIAO',
'CE',
'62389-000'
);

INSERT INTO CLIENTE VALUES (
'820',
'MECANICA SAO PAULO',
'R. DO MACUCO, 99',
'SANTO ANTONIO',
'ES',
'29810-020'
);

INSERT INTO CLIENTE VALUES (
'170',
'POSTO BRASIL LTDA.',
'AV. IMPERIO, 85',
'GUARIRUS',
'BA',
'42837-000'
);

INSERT INTO VENDA VALUES (
'230001',
1300.00,
'2001-06-10',
'250'
);

INSERT INTO VENDA VALUES (
'230099',
1000.00,
'2002-10-02',
'170'
);

INSERT INTO VENDA VALUES (
'997818',
3000.00,
'2001-11-11',
'820'
);

-- CONSULTAS (JUNÇÕS - JOIN)
SELECT venda.DUPLIC, cliente.NOME
FROM cliente, venda 
WHERE cliente.CODCLI = venda.CODCLI;

-- COM INER JOIN
SELECT venda.DUPLIC, cliente.NOME
FROM cliente INNER JOIN venda ON cliente.CODCLI = cliente.CODCLI;

-- COM ALIAS
SELECT ven.DUPLIC, cli.NOME
FROM cliente cli INNER JOIN venda ven ON cli.CODCLI = ven.CODCLI;

-- COM ORDEN BY 
SELECT ven.DUPLIC, cli.NOME 
FROM clente cli INNER JOIN venda ven ON cli.CODCLI = ven.CODCLI
ORDER BY cli.NOME;

-- RIGHT JOIN 
SELECT ven.DUPLIC, cli.NOME, cli.CIDADE
FROM cliente cli  RIGHT JOIN venda ven ON cli.CODCLI = ven.CODCLI
ORDER BY cli.NOME; 

-- LEFT JOIN 
SELECT ven.DUPLIC, cli.NOME, cli.CIDADE
FROM cliente cli LEFT JOIN venda ven ON cli.CODCLI = ven.CODCLI
ORDER BY cli.NOME; 

INSERT INTO CLIENTE VALUES (
'200',
'BANCO BAR CA S/A',
'R. VITOR, 340',
'SAO VIVIANE',
'SP',
'62389-123'
);

INSERT INTO CLIENTE VALUES (
'800',
'MECANICA SAO JOSE',
'R. DO MARIO, 99',
'SANTO BENEDITO',
'RS',
'29810-010'
);

-- QUANTIDADE
SELECT cliente.NOME, COUNT(*) AS QTDE
FROM cliente INNER JOIN venda ON cliente.CODCLI =
venda.CODCLI
GROUP BY cliente.NOME;

-- SOMA
SELECT cliente.NOME, SUM(VALOR) AS TOTAL
FROM cliente INNER JOIN venda ON cliente.CODCLI = venda.CODCLI
GROUP BY cliente.NOME;

