CREATE DATABASE AULA27;
USE AULA;

CREATE TABLE TabelaEX (
NOME VARCHAR (100)
);

CREATE TABLE TabelaFX (
NOME VARCHAR (100)
);

-- INSERIR DADOS
INSERT INTO TabelaEX VALUES ('Claúdia');
INSERT INTO TabelaEX VALUES ('Cadu');
INSERT INTO TabelaEX VALUES ('Bruno');
INSERT INTO TabelaEX VALUES ('Lucineia');
INSERT INTO TabelaEX VALUES ('Augusto');

INSERT INTO TabelaFX VALUES ('Amarildo');
INSERT INTO TabelaFX VALUES ('Alvaro');
INSERT INTO TabelaFX VALUES ('Bruno');
INSERT INTO TabelaFX VALUES ('Damares');
INSERT INTO TabelaFX VALUES ('Augusto');

-- INNER JOIN
SELECT EX.NOME, FX.NOME
FROM TABELAEX AS EX
INNER JOIN TABELAEX AS FX
ON EX.NOME = FX.NOME;

SELECT * FROM TABELAEX, TABELAFX;
 
-- LEFT JOIN 
SELECT EX.NOME, FX.NOME
FROM TABELAEX AS EX
LEFT JOIN TABELAFX AS FX 
ON EX.NOME = FX.NOME;

-- RIGHT JOIN
 SELECT EX.NOME, FX.NOME
FROM TABELAEX AS EX
RIGHT JOIN TABELAFX AS FX 
ON EX.NOME = FX.NOME;

--  LEFT JOIN COM NULL
SELECT EX.NOME, FX.NOME
FROM TABELAEX AS EX
LEFT JOIN TABELAFX AS FX 
     ON EX.NOME = FX.NOME
     WHERE FX.NOME IS NULL;
     
-- RIGHT JOIN COM NULL
SELECT EX.NOME, FX.NOME
FROM TABELAEX AS EX
RIGHT JOIN TABELAFX AS FX 
      ON EX.NOME = FX.NOME
      WHERE EX.NOME IS NULL;

