CREATE DATABASE LIMPEZA;

USE LIMPEZA;

CREATE TABLE CLIENTE (
COD_CLIENTE INT,
NOME_CLIENTES VARCHAR(100),
CPF VARCHAR (14),
ENDERECO VARCHAR (250),
CELULAR VARCHAR (18)
);

CREATE TABLE FUNCIONARIO (
COD_FUNCIONARIO INT,
CPF_FUNCIONARIO VARCHAR (14),
SALARIO VARCHAR (250),
NOME_FUNCIONARIO VARCHAR(100),
DATA_NASCIMENTO VARCHAR (10)
);

CREATE TABLE PRODUTO (
COD_PRODUTO INT,
VALOR VARCHAR (250),
QTDE VARCHAR (250),
DESCRICAO VARCHAR(250),
NOME_PRODUTO VARCHAR (100)
);

CREATE TABLE PEDIDOS (
COD_PEDIDO INT,
ID_PEDIDO VARCHAR (13),
HORARIO_ENTREGA VARCHAR (5),
VALOR VARCHAR (250),
DESCRICAO VARCHAR (250)
);

CREATE TABLE ESTOQUE (
COD_ESTOQUE INT,
POSICAO VARCHAR (10),
VALIDADE VARCHAR (10),
QTDE VARCHAR (250),
NOME_PRODUTO VARCHAR (100)
);

