CREATE DATABASE EXEMPLO3;

USE EXEMPLO3;

CREATE TABLE CLIENTE (
COD_CLIENTE INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_CLIENTE VARCHAR (100) NOT NULL,
CPF_CLIENTE VARCHAR (14) NOT NULL,
ENDERECO VARCHAR (100) NOT NULL,
ESTADO CHAR(2) DEFAULT 'SP',
CELULAR VARCHAR (19) NOT NULL
);

CREATE TABLE PRODUTOS (
COD_PRODUTOS  INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_PRODUTOS VARCHAR (255) NOT NULL,
QTDE INT,
DESCRICAO VARCHAR (255), 
VALOR DECIMAL (3,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
COD_FORNECEDOR INT AUTO_INCREMENT NOT NULL,
NOME_FORNECEDOR VARCHAR (100) NOT NULL, 
CIDADE CHAR(2) DEFAULT 'SP',
ESTADO CHAR(2) DEFAULT 'SP',
CNPJ VARCHAR (18) NOT NULL, 
CELULAR VARCHAR (19) NOT NULL,
ENDERECO VARCHAR (100) NOT NULL,
PRIMARY KEY (COD_FORNECEDOR)
);

CREATE TABLE TEM (
COD_TEM INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
COD_FORNECEDOR INT, 
COD_PRODUTO INT,
FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTOS (COD_PRODUTOS),
FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDORES (COD_FORNECEDOR)
);

-- CONSULTA DE TABELAS
SELECT * FROM PRODUTOS;

-- ALTERAÇÕES DE CAMPO 
ALTER TABLE CLIENTE
ADD SEXO CHAR(1);

ALTER TABLE CLIENTE
RENAME TO PESSOA_FISICA;

ALTER TABLE PESSOA_FISICA
CHANGE CPF CPFP VARCHAR(18);

ALTER TABLE PESSOA_FISICA
MODIFY COLUMN NOME_CLIENTE VARCHAR(150);


ALTER TABLE PESSOA_FISICA
MODIFY COLUMN ESTADO CHAR(2) DEFAULT 'SP';

-- REVISAR ALTERAÇÕES
-- ACRESCENTAR OS CAMPOS CIDADE EM PESSOA_FISICA
-- ALTERAR O CAMPO VALOR PRODUTOS PARA DECIMAL (7,2)
-- ACRESCENTAR O CAMPO CIDADE E ESTADO EM FORNECEDOR E DEFENIR 
-- O ESTADO COMO PADRÃO 'SP'

-- CORREÇÕES
-- 1)
ALTER TABLE PESSOA_FISICA
ADD CIDADE VARCHAR(60);

-- 2)
ALTER TABLE PRODUTOS
MODIFY COLUMN VALOR DECIMAL (7,2);

-- 3)
ALTER TABLE FORNECEDORES 
ADD CIDADE VARCHAR(60);

ALTER TABLE FORNECEDORES
ADD ESTADO CHAR (2) DEFAULT 'SP';

